version: "3.8"

x-default: &default
  restart: always
  tty: true
  env_file:
    - .env
  logging:
    driver: "json-file"
    options:
      max-size: "10M"
      max-file: "3"

services:
  app:
    <<: *default
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flarum
    volumes:
      - .:/var/www
      - ./deploy/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./deploy/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
#    depends_on:
#     - db

  nginx:
    <<: *default
    image: nginx:stable
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./deploy/nginx/.nginx.conf:/etc/nginx/.nginx.conf
      - ./deploy/nginx/flarum.conf:/etc/nginx/template/flarum.template
      - ./deploy/nginx/certificate:/etc/nginx/certs
    command: bash -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/template/flarum.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app

  db:
    <<: *default
    image: mariadb
    container_name: db
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - flarum_db:/var/lib/mysql

volumes:
  flarum_db:
    name: flarum_db_volume
